### PR TITLE
chore: update polkadot api version

### PR DESCRIPTION
**Pull request by rflechtner**
## fixes KILTProtocol/ticket#973
Updates the `@polkadot/api` version and applies some fixes for things that have changed.

## How to test:
unit & integration tests plus examples should run

## Checklist:

- [x] I have verified that the code works
- [x] I have verified that the code is easy to understand
  - [ ] If not, I have left a well-balanced amount of inline comments
- [ ] I have [left the code in a better state](https://deviq.com/boy-scout-rule/)
- [x] I have documented the changes (where applicable)

### CODE REVIEW

**Comment by rflechtner** [comment]
Turns out https://github.com/KILTprotocol/sdk-js/pull/325/commits/8b7db9d51dad3dc1498beec0ca886a4744daf505 wasn't actually necessary to make things work. Should I revert it or keep it? These are changes from the parachain branch.

**Comment by weichweich** [comment]
> Turns out [8b7db9d](https://github.com/KILTprotocol/sdk-js/commit/8b7db9d51dad3dc1498beec0ca886a4744daf505) wasn't actually necessary to make things work. Should I revert it or keep it? These are changes from the parachain branch.

If you verified that everything works without it, remove it. Making the SDK compatible with the parachain will be another PR.

**Comment by rflechtner** [comment]
> > Turns out [8b7db9d](https://github.com/KILTprotocol/sdk-js/commit/8b7db9d51dad3dc1498beec0ca886a4744daf505) wasn't actually necessary to make things work. Should I revert it or keep it? These are changes from the parachain branch.
> 
> If you verified that everything works without it, remove it. Making the SDK compatible with the parachain will be another PR.

Yes, test complete successfully. And the checks will run again, so there’s no need to worry

**Review by tjwelde — APPROVED** [review]
LGTM

**Pull request merged**
