### PR TITLE
feat!: remove all compression & decompression

### PR DESCRIPTION
**Pull request by tjwelde**
## fixes KILTProtocol/ticket#2165
We recommend using msgpack + gzip instead

## How to test:
- Tests run through

## Checklist:

- [x] I have verified that the code works
- [x] I have verified that the code is easy to understand
  - [ ] If not, I have left a well-balanced amount of inline comments
- [x] I have [left the code in a better state](https://deviq.com/principles/boy-scout-rule)
- [ ] I have documented the changes (where applicable)

### CODE REVIEW

**Review by arty-name — APPROVED** [review]
Could we drop jsonabc now?

**Comment by tjwelde** [comment]
Will check

**Review by rflechtner — APPROVED** [review]
LGTM

**Comment by rflechtner** [comment]
> Could we drop jsonabc now?

Don't think so, we need it to make sure Types serialise/hash consistently

**Comment by tjwelde** [comment]
It is still used indirectly in Quote and CType. To investigate, if those can be removed is a separate PR, I would say.

**Pull request merged**
