### PR TITLE
chore: release v1

### PR DESCRIPTION
**Pull request by rflechtner**
## 🚧 WIP 🚧 

Release branch for V1 of the SDK.

### TODOs before release:

- [x] Figure out what versions to use for non-V1'd sub-packages. We should leave some room for legacy support releases, so I went for `0.100.0` now, but can be discussed.
  - We have major breaking changes only on the following packages:
    - `@kiltprotocol/did`
    - `@kiltprotocol/types` (some types removed)
    - SDKErrors on `@kiltprotocol/utils`
    - `@kiltprotocol/vc-export` (but is planned to be renamed)
- [ ] Choose versioning strategy for sub-packages. E.g., pinning or tilde imports?
- [ ] Consider making other package imports and polkadot packages peer dependencies on sub-packages
- [x] rename `@kiltprotocol/vc-export` (https://github.com/KILTprotocol/sdk-js/pull/828)

### CODE REVIEW

**Comment by rflechtner** [comment]
### **Release Candidate Checklist**
1. [ ] Release rc-1
2. [ ] Communicate RC release and that applications should be tested against it on
    - [ ] Slack
    - [ ] Discord
3. [ ] Test docs/workshop against the rc version **using Peregrine**
    - [ ] Readmes
    - [ ] Getting-Started Guide
    - [ ] Workshop
4. [ ] Test dev Sporran against the rc version
5. [ ] Test dev SocialKYC against the rc version
6. [ ] Test DIDSign against rc version
7. [ ] Test Cookbook recipes against rc version
8. [ ] Test DID driver & stakeboard against rc version (if applicable)
8. [ ] Do SDK bundle tests (for testing browser / webpack compatibility)
9. [ ] Fix any issues, and repeat from step 1 increased rc-x to the next version
    - If fixes are needed in docs or apps, hold the release of them until the official sdk version is released

**Review by ntn-x2 — APPROVED** [review]
So we're only exporting the root SDK as v1?

**Review by ntn-x2 — APPROVED** [review]
So we're only exporting the root SDK as v1?

**Comment by rflechtner** [comment]
> So we're only exporting the root SDK as v1?

For now, yes

**Pull request closed without merging**
