### PR TITLE
chore: release 0.34.1

### PR DESCRIPTION
**Pull request by ntn-x2**
## Checklist

- [x] Publish rc -> https://www.npmjs.com/package/@kiltprotocol/sdk-js/v/0.35.0-rc.1
- [x] Unpublish/deprecate previous rc
- [x] Update metadata and type augmentation -> https://github.com/KILTprotocol/sdk-js/pull/821/commits/c72ba30741f226ebcedf1b9f29b8921493aef439
- [x] Cherry-pick https://github.com/KILTprotocol/sdk-js/pull/822
- [x] Review
- [x] Tag latest commit with `0.34.1-rc.1` -> https://github.com/KILTprotocol/sdk-js/tree/0.34.1-rc.1
- [x] Publish new rc -> https://www.npmjs.com/package/@kiltprotocol/sdk-js/v/0.34.1-rc.1
- [x] Run integration tests in dip-sdk using rc and `latest-develop` of peregrine and consumer-template
- [x] Release on Spiritnet
- [ ] Publish release
- [ ] Merge

### CODE REVIEW

**Review by rflechtner — COMMENTED** [review]
Looks good, we're planning to keep this an rc though until this gets released on spiritnet right ? otherwise we can't know if the runtime version number you put in there is going to be correct.

**Comment by ntn-x2** [comment]
@rflechtner our current release strategy do not capture this case when a feature is deployed on Peregrine and not on Spiritnet. Nevertheless, I don't see any blockers from making this a proper release. The new types and definitions will be in AT LEAST runtime 1.12, and also are not relevant if the runtime call is not present, which is the case for Spiritnet runtimes.
Plus, leaving this as an rc will delay Sporran integration, which is a fundamental component for integrators to, well, start integrating.

Why would you not make this an official release?

**Review by rflechtner — APPROVED** [review]
As discussed, feel free to publish this as an rc, which should be enough to start integration on testnets. We can stabilise this when the spiritnet release confirms the version ranges for the types.

**Comment by ntn-x2** [comment]
0.35 has been released, so this will also have to change to the new version.

**Comment by Dudleyneedham** [comment]
This seems irrelevant now.

**Comment by ntn-x2** [comment]
We migrated to a different repo and peer dependencies, this PR is not relevant anymore.

**Pull request closed without merging**
