### PR TITLE
refactor!: remove error types

### PR DESCRIPTION
**Pull request by Ad96el**
## fixes [KILTProtocol/ticket#2868](https://github.com/KILTprotocol/ticket/issues/2868)

BREAKING CHANGE: This PR removes error types that require users to update their code.

### CODE REVIEW

**Review by arty-name — COMMENTED** [review]
Should this be marked as a breaking change?

**Comment by arty-name** [comment]
> I would rather mark the first PR as a breaking change. How can I do that? 

The formatting rules for the commits are called [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/), and they also describe how to mark a commit as a breaking change. Since the other PR is already merged, it would have been too late to mark it as breaking, if it weren’t already. 

Still, both of these PRs are breaking, so I would mark this appropriately.

**Comment by rflechtner** [comment]
This removes errors that are now not thrown anywhere any more? Makes sense to remove them then

**Review by rflechtner — APPROVED** [review]
LGTM

**Review by arty-name — APPROVED** [review]

**Pull request merged**
