### PR TITLE
feat: add workshop test to CI

### PR DESCRIPTION
**Pull request by wischli**
## fixes KILTProtocol/ticket#625
- adds all example code from workshop (updated Substrate 2.0-compatible version) to CI testing
- design concept: when workshop code breaks in the CI, you can easily copy and paste the changes to the workshop markdown (this should not happen too often)
  - for each code snippet inside the SDK workshop files there exists a corresponding markdown comment in the workshop section, see example below
  - for each copy and paste there exists a distinct start `/* 🚧 2️⃣ COPY_START for attestationVerify_example (below this comment) 🚧  */` and end `/* 🚧 2️⃣ COPY_END for attestationVerify_example (above this comment) 🚧  */`
  - obviously some code has to be deleted/changed when adding to the workshop, all of these lines were marked with either `//❗️ UNCOMMENT-LINE in workshop ❗️` or `// ❗️ REMOVE-LINE in workshop ❗️`
  - as a result, some code looks really "ugly" because it is dependent on previous steps (e.g. attesting a claim) whereas in the tutorial you are required to copy and paste these results

##### Workshop `6_attestation.md`

```markdown
[comment]: <copy and paste 2️⃣ attestationVerify_example from 4_attestation.ts>
```

##### SDK-JS `src/__integrationtests__/workshop/4_attestation.ts`

```javascript
async function attestationVerify(
  requestForAttestation: Kilt.RequestForAttestation
) {
  /* 🚧 2️⃣ COPY_START for attestationVerify_example (below this comment) 🚧  */
  const isDataValid = requestForAttestation.verifyData()
  const isSignatureValid = requestForAttestation.verifySignature()
  console.log('isDataValid: ', isDataValid)
  console.log('isSignatureValid: ', isSignatureValid)
  /* 🚧 2️⃣ COPY_END for attestationVerify_example (above this comment) 🚧  */
}
```

## How to test:
1. Read and review my wiki entry on ["How to update code examples in the KILT workshop"](https://github.com/KILTprotocol/organizational/wiki/How-to-update-code-examples-in-the-KILT-workshop#2-apply-changes-from-workshop-to-sdk) to understand the design principles
2. Review together with [update of the workshop](https://github.com/KILTprotocol/kilt-workshop-101/pull/10). Compare [code snippets from SDK workshop CI](https://github.com/KILTprotocol/sdk-js/pull/287/files?file-filters%5B%5D=.json&file-filters%5B%5D=.ts) with those inside the workshop.

## Checklist:

- [x] I have verified that the code works
- [x] I have verified that the code is easy to understand
  - [ ] If not, I have left a well-balanced amount of inline comments
- [ ] I have [left the code in a better state](https://deviq.com/boy-scout-rule/)
- [x] I have documented the changes (where applicable)

### CODE REVIEW

**Comment by rflechtner** [comment]
sorry for meddling, but wouldn't it be neat to set up tests on the workshop repo itself and trigger them whenever the GitHub Packages release is updated, which would happen on pushes to develop ? [Github already has a trigger for that](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#registry_package).

**Comment by wischli** [comment]
> sorry for meddling, but wouldn't it be neat to set up tests on the workshop repo itself and trigger them whenever the GitHub Packages release of the sdk is updated, which would happen on pushes to develop ? [Github already has a trigger for that](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#registry_package).

Agree, will check out and implement.

**Comment by rflechtner** [comment]
there is also GitHub Action for creating issues, which we could set up to notify us of failing tests

**Comment by wischli** [comment]
Closing this in favor of [adding the CI directly to the workshop](https://github.com/KILTprotocol/kilt-workshop-101/pull/10) on each publish of a new github release, e.g. push to `develop`.

**Pull request closed without merging**
