### PR TITLE
docs: remove github docs publish

### PR DESCRIPTION
**Pull request by ChrisChinchilla**
## fixes KILTProtocol/ticket#3578

Move v1 SDK docs to Amplify and remove from GitHub pages.

### CODE REVIEW

**Comment by ChrisChinchilla** [comment]
These are now working

[kit-js.kilt.io](http://kit-js.kilt.io/)
[kilt-js-old.kilt.io](http://kilt-js-old.kilt.io/)

So this is ready to merge.

**Comment by ggera** [comment]
> These are now working
> 
> [kit-js.kilt.io](http://kit-js.kilt.io/) [kilt-js-old.kilt.io](http://kilt-js-old.kilt.io/)
> 
> So this is ready to merge.

Adios old page :rocket: , what is the strategy for href reference on the docs repo? Either replace

1.  [https://kiltprotocol.github.io/sdk-js/](https://kiltprotocol.github.io/sdk-js/) with  [https://kilt-js-old.kilt.io/)](https://kilt-js-old.kilt.io/) on `release-0.35.0` branch
2.  [https://kiltprotocol.github.io/sdk-js/](https://kiltprotocol.github.io/sdk-js/) with  [https://kilt-js.kilt.io/)](https://kilt-js.kilt.io/) on develop
or keep it as before and create a issue ticket to delete this github page

**Comment by rflechtner** [comment]
Any reason one is `kit-js` and the other `kilt-js` ? is that a typo or a deliberate choice?

**Review by rflechtner — APPROVED** [review]
In any case, removing this wf seems fine to me.

**Comment by ggera** [comment]
> Any reason one is `kit-js` and the other `kilt-js` ? is that a typo or a deliberate choice?

Typo, renamed it to `kilt-js.kilt.io`

**Review by ggera — APPROVED** [review]

**Pull request merged**
