### PR TITLE
chore: update and dedupe dependencies

### PR DESCRIPTION
**Pull request by ntn-x2**
Integration tests, e.g., [this one](https://github.com/KILTprotocol/sdk-js/actions/runs/3676228030/jobs/6216692783) have started to fail because the node `develop` image has upgraded polkadot dependencies to 0.9.32, and that has apparently some breaking changes which have been fixed in a polkadot version later than what we currently have in the SDK.

This PR updates the `@polkadot/api`-related dependencies to the latest published version, so it is possible to run integration tests against `develop` again.

### CODE REVIEW

**Comment by ntn-x2** [comment]
Not sure what's going on with the bundle tests, but I saw that this also happens in other PRs, so it's most likely unrelated to this one.

**Comment by arty-name** [comment]
Yeah, the bundle tests seem completely unrelated to your changes

**Review by arty-name — APPROVED** [review]

**Review by rflechtner — APPROVED** [review]
LGTM!

**Comment by rflechtner** [comment]
re/ the bundle tests, I think we need to bump playwright to ^1.21.1

https://github.com/microsoft/playwright/issues/13530#issuecomment-1098337227

**Pull request merged**
