### PR TITLE
feat: upgrade yarn to v2

### PR DESCRIPTION
**Pull request by tjwelde**
## fixes KILTProtocol/ticket#834
This PR upgrade our repo to yarn v2

## How to test:
- Update global yarn to latest version (global still uses a v1 version, v2 is used only locally)
- `yarn install`
- `yarn test`

## Checklist:

- [x] I have verified that the code works
- [x] I have verified that the code is easy to understand
  - [ ] If not, I have left a well-balanced amount of inline comments
- [x] I have [left the code in a better state](https://deviq.com/boy-scout-rule/)
- [ ] I have documented the changes (where applicable)

### CODE REVIEW

**Comment by rflechtner** [comment]
I'm having trouble executing `yarn test:integration` - can you check that?

**Comment by rflechtner** [comment]
> I'm having trouble executing `yarn test:integration` - can you check that?

I get this:
```
command not found: if
command not found: then
command not found: else
```
for a bunch of shells (sh, fish, bash, zsh...)

**Review by rflechtner — APPROVED** [review]
Works on my machine, package build works with demo client, tests are running.
Adding new packages is as easy as before. Love it!

We may have to update the integrations tests script thought

**Review by weichweich — APPROVED** [review]
Seems ok

**Comment by rflechtner** [comment]
just one last thing: is the way deps are currently cached (locally, in the repo) the best we can do? No way to link this to yarn's global cache?

**Comment by tjwelde** [comment]
yarn will redo the cache after first install

**Pull request merged**
