### PR TITLE
refactor!: integrate feedback on alpha release

### PR DESCRIPTION
**Pull request by rflechtner**
## fixes KILTProtocol/ticket#3540

- breaking: unnest selective disclosure parameters dc8d45865ca7d070f3d38a2451c16aff960a9b46
- breaking: fully switch to using named parameters on credentials functions 3c17ace73089be9b74458d6709881d576b33115b
- non-breaking: allow passing key pairs & signers as submitter parameter on `issue()` bcd882f8e5c10c0dc0d74946851072da1fd842aa

## How to test:

- Actually trying the new interfaces could be done on the beta that is to be released
- Tests for new features are yet to be written

## Checklist:

- [x] I have verified that the code works
- [x] I have verified that the code is easy to understand
  - [ ] If not, I have left a well-balanced amount of inline comments
- [x] I have [left the code in a better state](https://deviq.com/principles/boy-scout-rule)
- [ ] I have documented the changes (where applicable)
    * Either PR or Ticket to update [the Docs](https://github.com/KILTprotocol/docs)
    * Link the PR/Ticket here

### CODE REVIEW

**Review by abdulmth — APPROVED** [review]

**Comment by rflechtner** [comment]
@abdulmth I'm not sure about the nesting of parameters, seems cumbersome and messy to me. How did you see it? Should we flatten parameters a bit more?

**Review by Dudleyneedham — APPROVED** [review]
LGTM. It feels more consistent

**Comment by Dudleyneedham** [comment]
> @abdulmth I'm not sure about the nesting of parameters, seems cumbersome and messy to me. How did you see it? Should we flatten parameters a bit more?

I would argue to call them all options, that would move them up one level.

> I would keep the `issuer` and `holder` objects but maybe flatten the various options objects.

Yes, I would agree.

**Comment by rflechtner** [comment]
@abdulmth had argued that the proof/presentationOptions to carry semantic value. We did decide to group options this way at some point and I'm not sure we want to change that last minute without good reason, so I'd just leave it.

**Pull request merged**
