### PR TITLE
fix!: rename service endpoint URLs to URIs

### PR DESCRIPTION
**Pull request by arty-name**
## fixes KILTProtocol/ticket#1889

DID service endpoint URIs are not URLs.

## How to test:

yarn test

## Checklist:

- [x] I have verified that the code works
- [x] I have verified that the code is easy to understand
  - [ ] If not, I have left a well-balanced amount of inline comments
- [x] I have [left the code in a better state](https://deviq.com/principles/boy-scout-rule)
- [ ] I have documented the changes (where applicable)

### CODE REVIEW

**Review by ntn-x2 — APPROVED** [review]
LGTM!

**Comment by arty-name** [comment]
Hey @tjwelde, what do you think of the code changes? Is the upside of having a semantically correct property name worth the hassle of converting back and forth for light DIDs and for blockchain APIs? An alternative could be to only change texts.

**Comment by arty-name** [comment]
This looks like an approval :)

**Comment by arty-name** [comment]
Oh, I know, we have a serializationFlag in the light DID serialization code, this could be a perfect use for it!

**Review by tjwelde — APPROVED** [review]
LGTM

**Pull request merged**
